; exercise 6.2.1.5
; Write a program that contains two instructions: (1) add the number 5 to the EAX
; register, and (2) add 5 to the EDX register. Generate a listing file and examine the
; machine code generated by the assembler. What differences, if any, did you find
; between the two instructions?


.386
.model flat, stdcall
.stack 4096

ExitProcess PROTO, dwExitCode:DWORD

.code
main PROC
    mov eax, 0     ; Clear EAX
    add eax, 5     ; Instruction 1: add 5 to EAX

    mov edx, 0     ; Clear EDX
    add edx, 5     ; Instruction 2: add 5 to EDX

    INVOKE ExitProcess, 0
main ENDP

END main
